// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type FeedArticle struct {
	Created       time.Time `json:"created"`
	Published     time.Time `json:"published"`
	ResourceID    string    `json:"resource_id"`
	ResourceTitle string    `json:"resource_title"`
	Link          string    `json:"link"`
	Title         string    `json:"title"`
	Description   string    `json:"description"`
	Content       string    `json:"content"`
	Author        string    `json:"author"`
	Image         string    `json:"image"`
}

type FeedResource struct {
	URL       string    `json:"url"`
	Title     string    `json:"title"`
	Created   time.Time `json:"created"`
	Modified  time.Time `json:"modified"`
	Published time.Time `json:"published"`
	Active    bool      `json:"active"`
}

type NewResource struct {
	URL string `json:"url"`
}
